[package]
name = "the_last_hope"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ggez = "0.9"
libm = "0.2.8"
num = "0.4.1"
nalgebra = "0.32"
pathfinding = "4.7.0"
rand = "0.8.5"